spring.application.name=4you-ecom
spring.datasource.url=jdbc:mysql://localhost:3306/foryou_ecom
spring.datasource.username=root
spring.datasource.password=NewPasswordHere

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
